### ISSUE TITLE
luarock release ?

### ISSUE THREAD

**Issue by sourcevault** [spc476/lua-conmanorg#4]
Hi Sean !

Will it be possible to release it to luarocks ? so I could just do :

```
luarocks install lua-conmanorg
```

I hope you can see how easy it gets to install.

**Comment by spc476** [comment]
I know, some of the modules are already available as rocks:

*  `org.conman.cont.gopher-types`
* `org.conman.env`
* `org.conman.errno`
* `org.conman.iconv`
* `org.conman.syslog`
* `org.conman.tls`

I'm a bit relunctant to make them all available as some are still "works in progress".  And there are other modules under the `org.conman` namespace that aren't included in this repo, such as:

* `org.conman.cbor`
* `org.conman.uuid`
* Just about all modules under `org.conman.parsers` (another repo I have).

**Comment by sourcevault** [comment]
How would I include  `lua-conmanorg` to use this method ?

https://github.com/spc476/lua-conmanorg/blob/43692b440a974e2223f2b9886da440da6674cbc2/lua/table.lua#L131

Reading the doc it seems I need to do :

```lua
local table = require('org.conman.table')

local dump_value = table.dump_value
```

but based on what you say it seems its not publicly exposed ?

**Comment by spc476** [comment]
I don't have a luarocks file for `org.conman.table`---there's nothing about it not being publicly exposed.  When I said "I'm a bit relunctant to make them available" I meant "available via luarocks".  And I don't have a `org.conman` module---the "org.conman" is just a namespace for my modules to love under and not conflict with other modules.

But yes, once you have the modules in this repo installed you can do:

    local tab = require "org.conman.table" -- avoid shadowing standard table module
    local dump_value = tab.dump_value

**Comment by sourcevault** [comment]
Thank you for providing much needed information.
